import { createFileRoute, Link, useParams } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import { RequireAuth } from "@/components/auth/RequireAuth";
import { Navbar } from "@/components/layout/Navbar";
import { Logo } from "@/components/common/Logo";
import { Progress } from "@/components/ui/progress";
import { AIReportCardV2, type AIReportV2, type ReportMetaV2 } from "@/components/report/AIReportCardV2";
import { ExpertAnswerSection } from "@/components/report/ExpertAnswerSection";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";

const LOADING_STEPS = [
  "Connecting to live market data…",
  "Classifying your question…",
  "Fetching fundamentals & headlines…",
  "Running compliance guardrails…",
];

function LoadingScreen() {
  const [progress, setProgress] = useState(8);
  const [stepIdx, setStepIdx] = useState(0);
  useEffect(() => {
    const id = setInterval(() => {
      setProgress((p) => Math.min(p + 3, 92));
      setStepIdx((i) => (i + 1) % LOADING_STEPS.length);
    }, 900);
    return () => clearInterval(id);
  }, []);
  return (
    <div className="min-h-screen bg-mesh flex flex-col items-center justify-center gap-6 px-6 text-center">
      <div className="animate-pulse"><Logo size="lg" linkTo={null} /></div>
      <div className="w-full max-w-sm">
        <Progress value={progress} className="h-2" />
        <p className="mt-3 text-sm text-muted-foreground font-mono">{LOADING_STEPS[stepIdx]}</p>
      </div>
      <p className="text-xs text-muted-foreground italic max-w-md">Compliance-first AI · No hallucinated targets · SEBI analyst video arriving within 24h</p>
    </div>
  );
}

function ReportContent() {
  const { queryId } = useParams({ from: "/report/$queryId" });
  const { data, isLoading, error } = useQuery({
    queryKey: ["query-report", queryId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("queries")
        .select("id, stock_name, stock_symbol, buy_price, current_price, ai_report, created_at, status, assigned_analyst_id")
        .eq("id", queryId)
        .single();
      if (error) throw error;
      let analyst: { display_name: string; sebi_reg_number: string; avatar_url: string | null } | null = null;
      if (data.assigned_analyst_id) {
        const { data: a } = await supabase
          .from("analyst_profiles")
          .select("display_name, sebi_reg_number, avatar_url")
          .eq("id", data.assigned_analyst_id)
          .maybeSingle();
        analyst = a;
      }
      return { ...data, analyst };
    },
    refetchInterval: (q) => (q.state.data?.ai_report ? false : 1500),
  });

  if (isLoading || !data || !data.ai_report) return <LoadingScreen />;

  if (error) {
    return (
      <div className="min-h-screen flex items-center justify-center p-6">
        <div className="text-center max-w-md">
          <p className="font-display text-2xl">Couldn't load this report</p>
          <p className="text-muted-foreground mt-2 text-sm">{(error as Error).message}</p>
          <Button asChild className="mt-4"><Link to="/post-query">Post a new query</Link></Button>
        </div>
      </div>
    );
  }

  const meta: ReportMetaV2 = {
    id: data.id as string,
    createdAt: data.created_at as string,
    stockName: data.stock_name as string,
    stockSymbol: (data.stock_symbol as string | null) ?? null,
    buyPrice: data.buy_price as number | null,
    currentPrice: data.current_price as number | null,
    analystName: data.analyst?.display_name ?? null,
    analystSebi: data.analyst?.sebi_reg_number ?? null,
    analystAvatar: data.analyst?.avatar_url ?? null,
  };

  const rawReport = data.ai_report as Record<string, unknown>;
  const LEGACY_KEYS = [
    "verdict", "verdictColor", "tagline", "target1", "target2", "stopLoss", "stop_loss",
    "supportZone", "resistanceZone", "support_zone", "resistance_zone",
    "averagingZone", "freshEntryZone", "freshEntryTrigger", "ifHoldingAction",
    "ifAveragingRecommended", "closingInsight", "expertQuote", "pnlContext",
    "confidence", "riskScore", "rewardPotential", "momentum", "trend",
    "fundamentalPoints", "technicalPoints", "whatCanGoWrong", "behavioralReminder",
    "fundamentals", "technical", "risk", "timeHorizon",
  ];
  const isLegacy = LEGACY_KEYS.some((k) => k in (rawReport ?? {}));
  const safeReport: Record<string, unknown> = { ...rawReport };
  for (const k of LEGACY_KEYS) delete safeReport[k];

  return (
    <div className="min-h-screen bg-mesh">
      <Navbar />
      <main className="px-4 sm:px-6 lg:px-8 py-8 print:py-0">
        {isLegacy && (
          <div className="mx-auto max-w-4xl mb-4 rounded-xl border border-amber-500/40 bg-amber-500/10 px-4 py-3 text-sm text-amber-800 dark:text-amber-200">
            <strong>Legacy report:</strong> this query was generated by an older AI pipeline that included
            target / stop-loss / verdict fields. Those fields have been retired for SEBI compliance and are
            hidden. Please post a fresh query to get the new educational-context report.
          </div>
        )}
        <AIReportCardV2 report={safeReport as unknown as AIReportV2} meta={meta} />
        <ExpertAnswerSection
          queryId={data.id as string}
          assignedAnalystId={(data.assigned_analyst_id as string | null) ?? null}
          queryCreatedAt={data.created_at as string}
        />
      </main>
    </div>
  );
}

export const Route = createFileRoute("/report/$queryId")({
  head: () => ({ meta: [{ title: "AI Report — Stockera" }] }),
  component: () => <RequireAuth><ReportContent /></RequireAuth>,
});
