/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TopupRouteImport } from './routes/topup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StockPickerRouteImport } from './routes/stock-picker'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SebiComplianceRouteImport } from './routes/sebi-compliance'
import { Route as RiskDisclosureRouteImport } from './routes/risk-disclosure'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PostQueryRouteImport } from './routes/post-query'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MyQueriesRouteImport } from './routes/my-queries'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvestorCharterRouteImport } from './routes/investor-charter'
import { Route as GrievanceRedressalRouteImport } from './routes/grievance-redressal'
import { Route as FeeScheduleRouteImport } from './routes/fee-schedule'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DevChecklistRouteImport } from './routes/dev-checklist'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as VAnswerIdRouteImport } from './routes/v.$answerId'
import { Route as StockSymbolRouteImport } from './routes/stock.$symbol'
import { Route as ReportQueryIdRouteImport } from './routes/report.$queryId'
import { Route as RQueryIdRouteImport } from './routes/r.$queryId'
import { Route as PrintSymbolRouteImport } from './routes/print.$symbol'
import { Route as PrintStockQueryIdRouteImport } from './routes/print-stock.$queryId'
import { Route as PrintSectorQueryIdRouteImport } from './routes/print-sector.$queryId'
import { Route as PrintEducationalQueryIdRouteImport } from './routes/print-educational.$queryId'
import { Route as LibrarySymbolRouteImport } from './routes/library.$symbol'
import { Route as GeneralAnswerIdRouteImport } from './routes/general.$answerId'
import { Route as CuratedItemIdRouteImport } from './routes/curated.$itemId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AnalystAnalystIdRouteImport } from './routes/analyst.$analystId'
import { Route as AnalysisSymbolRouteImport } from './routes/analysis.$symbol'
import { Route as AdminVideosRouteImport } from './routes/admin.videos'
import { Route as AdminSuperRouteImport } from './routes/admin.super'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminExportsRouteImport } from './routes/admin.exports'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCuratedRouteImport } from './routes/admin.curated'
import { Route as AdminComposeVideoRouteImport } from './routes/admin.compose-video'
import { Route as AdminBacktestRouteImport } from './routes/admin.backtest'
import { Route as AdminApplyRouteImport } from './routes/admin.apply'
import { Route as DocsArchitecturePrintRouteImport } from './routes/docs.architecture.print'
import { Route as DocsAccuracyRoadmapPrintRouteImport } from './routes/docs.accuracy-roadmap.print'
import { Route as ApiLogoSymbolRouteImport } from './routes/api.logo.$symbol'
import { Route as AdminVideosNewRouteImport } from './routes/admin.videos.new'
import { Route as AdminUploadAnswerQueryIdRouteImport } from './routes/admin.upload-answer.$queryId'
import { Route as AdminCuratedNewRouteImport } from './routes/admin.curated.new'
import { Route as AdminVideosAnswerIdPreviewRouteImport } from './routes/admin.videos.$answerId.preview'
import { Route as AdminVideosAnswerIdEditRouteImport } from './routes/admin.videos.$answerId.edit'
import { Route as AdminCuratedItemIdEditRouteImport } from './routes/admin.curated.$itemId.edit'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TopupRoute = TopupRouteImport.update({
  id: '/topup',
  path: '/topup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StockPickerRoute = StockPickerRouteImport.update({
  id: '/stock-picker',
  path: '/stock-picker',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SebiComplianceRoute = SebiComplianceRouteImport.update({
  id: '/sebi-compliance',
  path: '/sebi-compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskDisclosureRoute = RiskDisclosureRouteImport.update({
  id: '/risk-disclosure',
  path: '/risk-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PostQueryRoute = PostQueryRouteImport.update({
  id: '/post-query',
  path: '/post-query',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MyQueriesRoute = MyQueriesRouteImport.update({
  id: '/my-queries',
  path: '/my-queries',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorCharterRoute = InvestorCharterRouteImport.update({
  id: '/investor-charter',
  path: '/investor-charter',
  getParentRoute: () => rootRouteImport,
} as any)
const GrievanceRedressalRoute = GrievanceRedressalRouteImport.update({
  id: '/grievance-redressal',
  path: '/grievance-redressal',
  getParentRoute: () => rootRouteImport,
} as any)
const FeeScheduleRoute = FeeScheduleRouteImport.update({
  id: '/fee-schedule',
  path: '/fee-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DevChecklistRoute = DevChecklistRouteImport.update({
  id: '/dev-checklist',
  path: '/dev-checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const VAnswerIdRoute = VAnswerIdRouteImport.update({
  id: '/v/$answerId',
  path: '/v/$answerId',
  getParentRoute: () => rootRouteImport,
} as any)
const StockSymbolRoute = StockSymbolRouteImport.update({
  id: '/stock/$symbol',
  path: '/stock/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportQueryIdRoute = ReportQueryIdRouteImport.update({
  id: '/report/$queryId',
  path: '/report/$queryId',
  getParentRoute: () => rootRouteImport,
} as any)
const RQueryIdRoute = RQueryIdRouteImport.update({
  id: '/r/$queryId',
  path: '/r/$queryId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintSymbolRoute = PrintSymbolRouteImport.update({
  id: '/print/$symbol',
  path: '/print/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintStockQueryIdRoute = PrintStockQueryIdRouteImport.update({
  id: '/print-stock/$queryId',
  path: '/print-stock/$queryId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintSectorQueryIdRoute = PrintSectorQueryIdRouteImport.update({
  id: '/print-sector/$queryId',
  path: '/print-sector/$queryId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintEducationalQueryIdRoute = PrintEducationalQueryIdRouteImport.update({
  id: '/print-educational/$queryId',
  path: '/print-educational/$queryId',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarySymbolRoute = LibrarySymbolRouteImport.update({
  id: '/library/$symbol',
  path: '/library/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneralAnswerIdRoute = GeneralAnswerIdRouteImport.update({
  id: '/general/$answerId',
  path: '/general/$answerId',
  getParentRoute: () => rootRouteImport,
} as any)
const CuratedItemIdRoute = CuratedItemIdRouteImport.update({
  id: '/curated/$itemId',
  path: '/curated/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalystAnalystIdRoute = AnalystAnalystIdRouteImport.update({
  id: '/analyst/$analystId',
  path: '/analyst/$analystId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisSymbolRoute = AnalysisSymbolRouteImport.update({
  id: '/analysis/$symbol',
  path: '/analysis/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/admin/videos',
  path: '/admin/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSuperRoute = AdminSuperRouteImport.update({
  id: '/admin/super',
  path: '/admin/super',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExportsRoute = AdminExportsRouteImport.update({
  id: '/admin/exports',
  path: '/admin/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCuratedRoute = AdminCuratedRouteImport.update({
  id: '/admin/curated',
  path: '/admin/curated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminComposeVideoRoute = AdminComposeVideoRouteImport.update({
  id: '/admin/compose-video',
  path: '/admin/compose-video',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBacktestRoute = AdminBacktestRouteImport.update({
  id: '/admin/backtest',
  path: '/admin/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplyRoute = AdminApplyRouteImport.update({
  id: '/admin/apply',
  path: '/admin/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsArchitecturePrintRoute = DocsArchitecturePrintRouteImport.update({
  id: '/docs/architecture/print',
  path: '/docs/architecture/print',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAccuracyRoadmapPrintRoute =
  DocsAccuracyRoadmapPrintRouteImport.update({
    id: '/docs/accuracy-roadmap/print',
    path: '/docs/accuracy-roadmap/print',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLogoSymbolRoute = ApiLogoSymbolRouteImport.update({
  id: '/api/logo/$symbol',
  path: '/api/logo/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVideosNewRoute = AdminVideosNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminVideosRoute,
} as any)
const AdminUploadAnswerQueryIdRoute =
  AdminUploadAnswerQueryIdRouteImport.update({
    id: '/admin/upload-answer/$queryId',
    path: '/admin/upload-answer/$queryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCuratedNewRoute = AdminCuratedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminCuratedRoute,
} as any)
const AdminVideosAnswerIdPreviewRoute =
  AdminVideosAnswerIdPreviewRouteImport.update({
    id: '/$answerId/preview',
    path: '/$answerId/preview',
    getParentRoute: () => AdminVideosRoute,
  } as any)
const AdminVideosAnswerIdEditRoute = AdminVideosAnswerIdEditRouteImport.update({
  id: '/$answerId/edit',
  path: '/$answerId/edit',
  getParentRoute: () => AdminVideosRoute,
} as any)
const AdminCuratedItemIdEditRoute = AdminCuratedItemIdEditRouteImport.update({
  id: '/$itemId/edit',
  path: '/$itemId/edit',
  getParentRoute: () => AdminCuratedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRoute
  '/dev-checklist': typeof DevChecklistRoute
  '/discover': typeof DiscoverRoute
  '/faq': typeof FaqRoute
  '/fee-schedule': typeof FeeScheduleRoute
  '/grievance-redressal': typeof GrievanceRedressalRoute
  '/investor-charter': typeof InvestorCharterRoute
  '/login': typeof LoginRoute
  '/my-queries': typeof MyQueriesRoute
  '/portfolio': typeof PortfolioRoute
  '/post-query': typeof PostQueryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/referral': typeof ReferralRoute
  '/risk-disclosure': typeof RiskDisclosureRoute
  '/sebi-compliance': typeof SebiComplianceRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stock-picker': typeof StockPickerRoute
  '/terms': typeof TermsRoute
  '/topup': typeof TopupRoute
  '/wallet': typeof WalletRoute
  '/watchlist': typeof WatchlistRoute
  '/admin/apply': typeof AdminApplyRoute
  '/admin/backtest': typeof AdminBacktestRoute
  '/admin/compose-video': typeof AdminComposeVideoRoute
  '/admin/curated': typeof AdminCuratedRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exports': typeof AdminExportsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/super': typeof AdminSuperRoute
  '/admin/videos': typeof AdminVideosRouteWithChildren
  '/analysis/$symbol': typeof AnalysisSymbolRoute
  '/analyst/$analystId': typeof AnalystAnalystIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/curated/$itemId': typeof CuratedItemIdRoute
  '/general/$answerId': typeof GeneralAnswerIdRoute
  '/library/$symbol': typeof LibrarySymbolRoute
  '/print-educational/$queryId': typeof PrintEducationalQueryIdRoute
  '/print-sector/$queryId': typeof PrintSectorQueryIdRoute
  '/print-stock/$queryId': typeof PrintStockQueryIdRoute
  '/print/$symbol': typeof PrintSymbolRoute
  '/r/$queryId': typeof RQueryIdRoute
  '/report/$queryId': typeof ReportQueryIdRoute
  '/stock/$symbol': typeof StockSymbolRoute
  '/v/$answerId': typeof VAnswerIdRoute
  '/library/': typeof LibraryIndexRoute
  '/admin/curated/new': typeof AdminCuratedNewRoute
  '/admin/upload-answer/$queryId': typeof AdminUploadAnswerQueryIdRoute
  '/admin/videos/new': typeof AdminVideosNewRoute
  '/api/logo/$symbol': typeof ApiLogoSymbolRoute
  '/docs/accuracy-roadmap/print': typeof DocsAccuracyRoadmapPrintRoute
  '/docs/architecture/print': typeof DocsArchitecturePrintRoute
  '/admin/curated/$itemId/edit': typeof AdminCuratedItemIdEditRoute
  '/admin/videos/$answerId/edit': typeof AdminVideosAnswerIdEditRoute
  '/admin/videos/$answerId/preview': typeof AdminVideosAnswerIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRoute
  '/dev-checklist': typeof DevChecklistRoute
  '/discover': typeof DiscoverRoute
  '/faq': typeof FaqRoute
  '/fee-schedule': typeof FeeScheduleRoute
  '/grievance-redressal': typeof GrievanceRedressalRoute
  '/investor-charter': typeof InvestorCharterRoute
  '/login': typeof LoginRoute
  '/my-queries': typeof MyQueriesRoute
  '/portfolio': typeof PortfolioRoute
  '/post-query': typeof PostQueryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/referral': typeof ReferralRoute
  '/risk-disclosure': typeof RiskDisclosureRoute
  '/sebi-compliance': typeof SebiComplianceRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stock-picker': typeof StockPickerRoute
  '/terms': typeof TermsRoute
  '/topup': typeof TopupRoute
  '/wallet': typeof WalletRoute
  '/watchlist': typeof WatchlistRoute
  '/admin/apply': typeof AdminApplyRoute
  '/admin/backtest': typeof AdminBacktestRoute
  '/admin/compose-video': typeof AdminComposeVideoRoute
  '/admin/curated': typeof AdminCuratedRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exports': typeof AdminExportsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/super': typeof AdminSuperRoute
  '/admin/videos': typeof AdminVideosRouteWithChildren
  '/analysis/$symbol': typeof AnalysisSymbolRoute
  '/analyst/$analystId': typeof AnalystAnalystIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/curated/$itemId': typeof CuratedItemIdRoute
  '/general/$answerId': typeof GeneralAnswerIdRoute
  '/library/$symbol': typeof LibrarySymbolRoute
  '/print-educational/$queryId': typeof PrintEducationalQueryIdRoute
  '/print-sector/$queryId': typeof PrintSectorQueryIdRoute
  '/print-stock/$queryId': typeof PrintStockQueryIdRoute
  '/print/$symbol': typeof PrintSymbolRoute
  '/r/$queryId': typeof RQueryIdRoute
  '/report/$queryId': typeof ReportQueryIdRoute
  '/stock/$symbol': typeof StockSymbolRoute
  '/v/$answerId': typeof VAnswerIdRoute
  '/library': typeof LibraryIndexRoute
  '/admin/curated/new': typeof AdminCuratedNewRoute
  '/admin/upload-answer/$queryId': typeof AdminUploadAnswerQueryIdRoute
  '/admin/videos/new': typeof AdminVideosNewRoute
  '/api/logo/$symbol': typeof ApiLogoSymbolRoute
  '/docs/accuracy-roadmap/print': typeof DocsAccuracyRoadmapPrintRoute
  '/docs/architecture/print': typeof DocsArchitecturePrintRoute
  '/admin/curated/$itemId/edit': typeof AdminCuratedItemIdEditRoute
  '/admin/videos/$answerId/edit': typeof AdminVideosAnswerIdEditRoute
  '/admin/videos/$answerId/preview': typeof AdminVideosAnswerIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRoute
  '/dev-checklist': typeof DevChecklistRoute
  '/discover': typeof DiscoverRoute
  '/faq': typeof FaqRoute
  '/fee-schedule': typeof FeeScheduleRoute
  '/grievance-redressal': typeof GrievanceRedressalRoute
  '/investor-charter': typeof InvestorCharterRoute
  '/login': typeof LoginRoute
  '/my-queries': typeof MyQueriesRoute
  '/portfolio': typeof PortfolioRoute
  '/post-query': typeof PostQueryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/referral': typeof ReferralRoute
  '/risk-disclosure': typeof RiskDisclosureRoute
  '/sebi-compliance': typeof SebiComplianceRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stock-picker': typeof StockPickerRoute
  '/terms': typeof TermsRoute
  '/topup': typeof TopupRoute
  '/wallet': typeof WalletRoute
  '/watchlist': typeof WatchlistRoute
  '/admin/apply': typeof AdminApplyRoute
  '/admin/backtest': typeof AdminBacktestRoute
  '/admin/compose-video': typeof AdminComposeVideoRoute
  '/admin/curated': typeof AdminCuratedRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exports': typeof AdminExportsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/super': typeof AdminSuperRoute
  '/admin/videos': typeof AdminVideosRouteWithChildren
  '/analysis/$symbol': typeof AnalysisSymbolRoute
  '/analyst/$analystId': typeof AnalystAnalystIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/curated/$itemId': typeof CuratedItemIdRoute
  '/general/$answerId': typeof GeneralAnswerIdRoute
  '/library/$symbol': typeof LibrarySymbolRoute
  '/print-educational/$queryId': typeof PrintEducationalQueryIdRoute
  '/print-sector/$queryId': typeof PrintSectorQueryIdRoute
  '/print-stock/$queryId': typeof PrintStockQueryIdRoute
  '/print/$symbol': typeof PrintSymbolRoute
  '/r/$queryId': typeof RQueryIdRoute
  '/report/$queryId': typeof ReportQueryIdRoute
  '/stock/$symbol': typeof StockSymbolRoute
  '/v/$answerId': typeof VAnswerIdRoute
  '/library/': typeof LibraryIndexRoute
  '/admin/curated/new': typeof AdminCuratedNewRoute
  '/admin/upload-answer/$queryId': typeof AdminUploadAnswerQueryIdRoute
  '/admin/videos/new': typeof AdminVideosNewRoute
  '/api/logo/$symbol': typeof ApiLogoSymbolRoute
  '/docs/accuracy-roadmap/print': typeof DocsAccuracyRoadmapPrintRoute
  '/docs/architecture/print': typeof DocsArchitecturePrintRoute
  '/admin/curated/$itemId/edit': typeof AdminCuratedItemIdEditRoute
  '/admin/videos/$answerId/edit': typeof AdminVideosAnswerIdEditRoute
  '/admin/videos/$answerId/preview': typeof AdminVideosAnswerIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/dashboard'
    | '/dev-checklist'
    | '/discover'
    | '/faq'
    | '/fee-schedule'
    | '/grievance-redressal'
    | '/investor-charter'
    | '/login'
    | '/my-queries'
    | '/portfolio'
    | '/post-query'
    | '/pricing'
    | '/privacy'
    | '/referral'
    | '/risk-disclosure'
    | '/sebi-compliance'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/stock-picker'
    | '/terms'
    | '/topup'
    | '/wallet'
    | '/watchlist'
    | '/admin/apply'
    | '/admin/backtest'
    | '/admin/compose-video'
    | '/admin/curated'
    | '/admin/dashboard'
    | '/admin/exports'
    | '/admin/login'
    | '/admin/profile'
    | '/admin/super'
    | '/admin/videos'
    | '/analysis/$symbol'
    | '/analyst/$analystId'
    | '/auth/callback'
    | '/curated/$itemId'
    | '/general/$answerId'
    | '/library/$symbol'
    | '/print-educational/$queryId'
    | '/print-sector/$queryId'
    | '/print-stock/$queryId'
    | '/print/$symbol'
    | '/r/$queryId'
    | '/report/$queryId'
    | '/stock/$symbol'
    | '/v/$answerId'
    | '/library/'
    | '/admin/curated/new'
    | '/admin/upload-answer/$queryId'
    | '/admin/videos/new'
    | '/api/logo/$symbol'
    | '/docs/accuracy-roadmap/print'
    | '/docs/architecture/print'
    | '/admin/curated/$itemId/edit'
    | '/admin/videos/$answerId/edit'
    | '/admin/videos/$answerId/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/dashboard'
    | '/dev-checklist'
    | '/discover'
    | '/faq'
    | '/fee-schedule'
    | '/grievance-redressal'
    | '/investor-charter'
    | '/login'
    | '/my-queries'
    | '/portfolio'
    | '/post-query'
    | '/pricing'
    | '/privacy'
    | '/referral'
    | '/risk-disclosure'
    | '/sebi-compliance'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/stock-picker'
    | '/terms'
    | '/topup'
    | '/wallet'
    | '/watchlist'
    | '/admin/apply'
    | '/admin/backtest'
    | '/admin/compose-video'
    | '/admin/curated'
    | '/admin/dashboard'
    | '/admin/exports'
    | '/admin/login'
    | '/admin/profile'
    | '/admin/super'
    | '/admin/videos'
    | '/analysis/$symbol'
    | '/analyst/$analystId'
    | '/auth/callback'
    | '/curated/$itemId'
    | '/general/$answerId'
    | '/library/$symbol'
    | '/print-educational/$queryId'
    | '/print-sector/$queryId'
    | '/print-stock/$queryId'
    | '/print/$symbol'
    | '/r/$queryId'
    | '/report/$queryId'
    | '/stock/$symbol'
    | '/v/$answerId'
    | '/library'
    | '/admin/curated/new'
    | '/admin/upload-answer/$queryId'
    | '/admin/videos/new'
    | '/api/logo/$symbol'
    | '/docs/accuracy-roadmap/print'
    | '/docs/architecture/print'
    | '/admin/curated/$itemId/edit'
    | '/admin/videos/$answerId/edit'
    | '/admin/videos/$answerId/preview'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/dashboard'
    | '/dev-checklist'
    | '/discover'
    | '/faq'
    | '/fee-schedule'
    | '/grievance-redressal'
    | '/investor-charter'
    | '/login'
    | '/my-queries'
    | '/portfolio'
    | '/post-query'
    | '/pricing'
    | '/privacy'
    | '/referral'
    | '/risk-disclosure'
    | '/sebi-compliance'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/stock-picker'
    | '/terms'
    | '/topup'
    | '/wallet'
    | '/watchlist'
    | '/admin/apply'
    | '/admin/backtest'
    | '/admin/compose-video'
    | '/admin/curated'
    | '/admin/dashboard'
    | '/admin/exports'
    | '/admin/login'
    | '/admin/profile'
    | '/admin/super'
    | '/admin/videos'
    | '/analysis/$symbol'
    | '/analyst/$analystId'
    | '/auth/callback'
    | '/curated/$itemId'
    | '/general/$answerId'
    | '/library/$symbol'
    | '/print-educational/$queryId'
    | '/print-sector/$queryId'
    | '/print-stock/$queryId'
    | '/print/$symbol'
    | '/r/$queryId'
    | '/report/$queryId'
    | '/stock/$symbol'
    | '/v/$answerId'
    | '/library/'
    | '/admin/curated/new'
    | '/admin/upload-answer/$queryId'
    | '/admin/videos/new'
    | '/api/logo/$symbol'
    | '/docs/accuracy-roadmap/print'
    | '/docs/architecture/print'
    | '/admin/curated/$itemId/edit'
    | '/admin/videos/$answerId/edit'
    | '/admin/videos/$answerId/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  DashboardRoute: typeof DashboardRoute
  DevChecklistRoute: typeof DevChecklistRoute
  DiscoverRoute: typeof DiscoverRoute
  FaqRoute: typeof FaqRoute
  FeeScheduleRoute: typeof FeeScheduleRoute
  GrievanceRedressalRoute: typeof GrievanceRedressalRoute
  InvestorCharterRoute: typeof InvestorCharterRoute
  LoginRoute: typeof LoginRoute
  MyQueriesRoute: typeof MyQueriesRoute
  PortfolioRoute: typeof PortfolioRoute
  PostQueryRoute: typeof PostQueryRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ReferralRoute: typeof ReferralRoute
  RiskDisclosureRoute: typeof RiskDisclosureRoute
  SebiComplianceRoute: typeof SebiComplianceRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StockPickerRoute: typeof StockPickerRoute
  TermsRoute: typeof TermsRoute
  TopupRoute: typeof TopupRoute
  WalletRoute: typeof WalletRoute
  WatchlistRoute: typeof WatchlistRoute
  AdminApplyRoute: typeof AdminApplyRoute
  AdminBacktestRoute: typeof AdminBacktestRoute
  AdminComposeVideoRoute: typeof AdminComposeVideoRoute
  AdminCuratedRoute: typeof AdminCuratedRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminExportsRoute: typeof AdminExportsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSuperRoute: typeof AdminSuperRoute
  AdminVideosRoute: typeof AdminVideosRouteWithChildren
  AnalysisSymbolRoute: typeof AnalysisSymbolRoute
  AnalystAnalystIdRoute: typeof AnalystAnalystIdRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CuratedItemIdRoute: typeof CuratedItemIdRoute
  GeneralAnswerIdRoute: typeof GeneralAnswerIdRoute
  LibrarySymbolRoute: typeof LibrarySymbolRoute
  PrintEducationalQueryIdRoute: typeof PrintEducationalQueryIdRoute
  PrintSectorQueryIdRoute: typeof PrintSectorQueryIdRoute
  PrintStockQueryIdRoute: typeof PrintStockQueryIdRoute
  PrintSymbolRoute: typeof PrintSymbolRoute
  RQueryIdRoute: typeof RQueryIdRoute
  ReportQueryIdRoute: typeof ReportQueryIdRoute
  StockSymbolRoute: typeof StockSymbolRoute
  VAnswerIdRoute: typeof VAnswerIdRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  AdminUploadAnswerQueryIdRoute: typeof AdminUploadAnswerQueryIdRoute
  ApiLogoSymbolRoute: typeof ApiLogoSymbolRoute
  DocsAccuracyRoadmapPrintRoute: typeof DocsAccuracyRoadmapPrintRoute
  DocsArchitecturePrintRoute: typeof DocsArchitecturePrintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topup': {
      id: '/topup'
      path: '/topup'
      fullPath: '/topup'
      preLoaderRoute: typeof TopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-picker': {
      id: '/stock-picker'
      path: '/stock-picker'
      fullPath: '/stock-picker'
      preLoaderRoute: typeof StockPickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sebi-compliance': {
      id: '/sebi-compliance'
      path: '/sebi-compliance'
      fullPath: '/sebi-compliance'
      preLoaderRoute: typeof SebiComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-disclosure': {
      id: '/risk-disclosure'
      path: '/risk-disclosure'
      fullPath: '/risk-disclosure'
      preLoaderRoute: typeof RiskDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-query': {
      id: '/post-query'
      path: '/post-query'
      fullPath: '/post-query'
      preLoaderRoute: typeof PostQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-queries': {
      id: '/my-queries'
      path: '/my-queries'
      fullPath: '/my-queries'
      preLoaderRoute: typeof MyQueriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investor-charter': {
      id: '/investor-charter'
      path: '/investor-charter'
      fullPath: '/investor-charter'
      preLoaderRoute: typeof InvestorCharterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grievance-redressal': {
      id: '/grievance-redressal'
      path: '/grievance-redressal'
      fullPath: '/grievance-redressal'
      preLoaderRoute: typeof GrievanceRedressalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fee-schedule': {
      id: '/fee-schedule'
      path: '/fee-schedule'
      fullPath: '/fee-schedule'
      preLoaderRoute: typeof FeeScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-checklist': {
      id: '/dev-checklist'
      path: '/dev-checklist'
      fullPath: '/dev-checklist'
      preLoaderRoute: typeof DevChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$answerId': {
      id: '/v/$answerId'
      path: '/v/$answerId'
      fullPath: '/v/$answerId'
      preLoaderRoute: typeof VAnswerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/$symbol': {
      id: '/stock/$symbol'
      path: '/stock/$symbol'
      fullPath: '/stock/$symbol'
      preLoaderRoute: typeof StockSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$queryId': {
      id: '/report/$queryId'
      path: '/report/$queryId'
      fullPath: '/report/$queryId'
      preLoaderRoute: typeof ReportQueryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$queryId': {
      id: '/r/$queryId'
      path: '/r/$queryId'
      fullPath: '/r/$queryId'
      preLoaderRoute: typeof RQueryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/$symbol': {
      id: '/print/$symbol'
      path: '/print/$symbol'
      fullPath: '/print/$symbol'
      preLoaderRoute: typeof PrintSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-stock/$queryId': {
      id: '/print-stock/$queryId'
      path: '/print-stock/$queryId'
      fullPath: '/print-stock/$queryId'
      preLoaderRoute: typeof PrintStockQueryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-sector/$queryId': {
      id: '/print-sector/$queryId'
      path: '/print-sector/$queryId'
      fullPath: '/print-sector/$queryId'
      preLoaderRoute: typeof PrintSectorQueryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-educational/$queryId': {
      id: '/print-educational/$queryId'
      path: '/print-educational/$queryId'
      fullPath: '/print-educational/$queryId'
      preLoaderRoute: typeof PrintEducationalQueryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$symbol': {
      id: '/library/$symbol'
      path: '/library/$symbol'
      fullPath: '/library/$symbol'
      preLoaderRoute: typeof LibrarySymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/general/$answerId': {
      id: '/general/$answerId'
      path: '/general/$answerId'
      fullPath: '/general/$answerId'
      preLoaderRoute: typeof GeneralAnswerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curated/$itemId': {
      id: '/curated/$itemId'
      path: '/curated/$itemId'
      fullPath: '/curated/$itemId'
      preLoaderRoute: typeof CuratedItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyst/$analystId': {
      id: '/analyst/$analystId'
      path: '/analyst/$analystId'
      fullPath: '/analyst/$analystId'
      preLoaderRoute: typeof AnalystAnalystIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$symbol': {
      id: '/analysis/$symbol'
      path: '/analysis/$symbol'
      fullPath: '/analysis/$symbol'
      preLoaderRoute: typeof AnalysisSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/admin/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/super': {
      id: '/admin/super'
      path: '/admin/super'
      fullPath: '/admin/super'
      preLoaderRoute: typeof AdminSuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/exports': {
      id: '/admin/exports'
      path: '/admin/exports'
      fullPath: '/admin/exports'
      preLoaderRoute: typeof AdminExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/curated': {
      id: '/admin/curated'
      path: '/admin/curated'
      fullPath: '/admin/curated'
      preLoaderRoute: typeof AdminCuratedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/compose-video': {
      id: '/admin/compose-video'
      path: '/admin/compose-video'
      fullPath: '/admin/compose-video'
      preLoaderRoute: typeof AdminComposeVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/backtest': {
      id: '/admin/backtest'
      path: '/admin/backtest'
      fullPath: '/admin/backtest'
      preLoaderRoute: typeof AdminBacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/apply': {
      id: '/admin/apply'
      path: '/admin/apply'
      fullPath: '/admin/apply'
      preLoaderRoute: typeof AdminApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/architecture/print': {
      id: '/docs/architecture/print'
      path: '/docs/architecture/print'
      fullPath: '/docs/architecture/print'
      preLoaderRoute: typeof DocsArchitecturePrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/accuracy-roadmap/print': {
      id: '/docs/accuracy-roadmap/print'
      path: '/docs/accuracy-roadmap/print'
      fullPath: '/docs/accuracy-roadmap/print'
      preLoaderRoute: typeof DocsAccuracyRoadmapPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logo/$symbol': {
      id: '/api/logo/$symbol'
      path: '/api/logo/$symbol'
      fullPath: '/api/logo/$symbol'
      preLoaderRoute: typeof ApiLogoSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/videos/new': {
      id: '/admin/videos/new'
      path: '/new'
      fullPath: '/admin/videos/new'
      preLoaderRoute: typeof AdminVideosNewRouteImport
      parentRoute: typeof AdminVideosRoute
    }
    '/admin/upload-answer/$queryId': {
      id: '/admin/upload-answer/$queryId'
      path: '/admin/upload-answer/$queryId'
      fullPath: '/admin/upload-answer/$queryId'
      preLoaderRoute: typeof AdminUploadAnswerQueryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/curated/new': {
      id: '/admin/curated/new'
      path: '/new'
      fullPath: '/admin/curated/new'
      preLoaderRoute: typeof AdminCuratedNewRouteImport
      parentRoute: typeof AdminCuratedRoute
    }
    '/admin/videos/$answerId/preview': {
      id: '/admin/videos/$answerId/preview'
      path: '/$answerId/preview'
      fullPath: '/admin/videos/$answerId/preview'
      preLoaderRoute: typeof AdminVideosAnswerIdPreviewRouteImport
      parentRoute: typeof AdminVideosRoute
    }
    '/admin/videos/$answerId/edit': {
      id: '/admin/videos/$answerId/edit'
      path: '/$answerId/edit'
      fullPath: '/admin/videos/$answerId/edit'
      preLoaderRoute: typeof AdminVideosAnswerIdEditRouteImport
      parentRoute: typeof AdminVideosRoute
    }
    '/admin/curated/$itemId/edit': {
      id: '/admin/curated/$itemId/edit'
      path: '/$itemId/edit'
      fullPath: '/admin/curated/$itemId/edit'
      preLoaderRoute: typeof AdminCuratedItemIdEditRouteImport
      parentRoute: typeof AdminCuratedRoute
    }
  }
}

interface AdminCuratedRouteChildren {
  AdminCuratedNewRoute: typeof AdminCuratedNewRoute
  AdminCuratedItemIdEditRoute: typeof AdminCuratedItemIdEditRoute
}

const AdminCuratedRouteChildren: AdminCuratedRouteChildren = {
  AdminCuratedNewRoute: AdminCuratedNewRoute,
  AdminCuratedItemIdEditRoute: AdminCuratedItemIdEditRoute,
}

const AdminCuratedRouteWithChildren = AdminCuratedRoute._addFileChildren(
  AdminCuratedRouteChildren,
)

interface AdminVideosRouteChildren {
  AdminVideosNewRoute: typeof AdminVideosNewRoute
  AdminVideosAnswerIdEditRoute: typeof AdminVideosAnswerIdEditRoute
  AdminVideosAnswerIdPreviewRoute: typeof AdminVideosAnswerIdPreviewRoute
}

const AdminVideosRouteChildren: AdminVideosRouteChildren = {
  AdminVideosNewRoute: AdminVideosNewRoute,
  AdminVideosAnswerIdEditRoute: AdminVideosAnswerIdEditRoute,
  AdminVideosAnswerIdPreviewRoute: AdminVideosAnswerIdPreviewRoute,
}

const AdminVideosRouteWithChildren = AdminVideosRoute._addFileChildren(
  AdminVideosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  DashboardRoute: DashboardRoute,
  DevChecklistRoute: DevChecklistRoute,
  DiscoverRoute: DiscoverRoute,
  FaqRoute: FaqRoute,
  FeeScheduleRoute: FeeScheduleRoute,
  GrievanceRedressalRoute: GrievanceRedressalRoute,
  InvestorCharterRoute: InvestorCharterRoute,
  LoginRoute: LoginRoute,
  MyQueriesRoute: MyQueriesRoute,
  PortfolioRoute: PortfolioRoute,
  PostQueryRoute: PostQueryRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ReferralRoute: ReferralRoute,
  RiskDisclosureRoute: RiskDisclosureRoute,
  SebiComplianceRoute: SebiComplianceRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StockPickerRoute: StockPickerRoute,
  TermsRoute: TermsRoute,
  TopupRoute: TopupRoute,
  WalletRoute: WalletRoute,
  WatchlistRoute: WatchlistRoute,
  AdminApplyRoute: AdminApplyRoute,
  AdminBacktestRoute: AdminBacktestRoute,
  AdminComposeVideoRoute: AdminComposeVideoRoute,
  AdminCuratedRoute: AdminCuratedRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminExportsRoute: AdminExportsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSuperRoute: AdminSuperRoute,
  AdminVideosRoute: AdminVideosRouteWithChildren,
  AnalysisSymbolRoute: AnalysisSymbolRoute,
  AnalystAnalystIdRoute: AnalystAnalystIdRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CuratedItemIdRoute: CuratedItemIdRoute,
  GeneralAnswerIdRoute: GeneralAnswerIdRoute,
  LibrarySymbolRoute: LibrarySymbolRoute,
  PrintEducationalQueryIdRoute: PrintEducationalQueryIdRoute,
  PrintSectorQueryIdRoute: PrintSectorQueryIdRoute,
  PrintStockQueryIdRoute: PrintStockQueryIdRoute,
  PrintSymbolRoute: PrintSymbolRoute,
  RQueryIdRoute: RQueryIdRoute,
  ReportQueryIdRoute: ReportQueryIdRoute,
  StockSymbolRoute: StockSymbolRoute,
  VAnswerIdRoute: VAnswerIdRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  AdminUploadAnswerQueryIdRoute: AdminUploadAnswerQueryIdRoute,
  ApiLogoSymbolRoute: ApiLogoSymbolRoute,
  DocsAccuracyRoadmapPrintRoute: DocsAccuracyRoadmapPrintRoute,
  DocsArchitecturePrintRoute: DocsArchitecturePrintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
