
-- 1) Restore EXECUTE on RLS helper functions. These are SECURITY DEFINER with
--    locked search_path; revoking from authenticated broke every RLS policy
--    that calls them, producing 403 "permission denied for function has_role".
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.get_user_role(uuid) TO authenticated;

-- 2) Replace handle_new_user to also process referral codes atomically.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  _ref_code text;
  _referrer_id uuid;
  _referrer_new_balance integer;
  _referee_new_balance integer;
BEGIN
  -- Create profile (referral_code auto-generated by column default)
  INSERT INTO public.profiles (id, full_name, phone)
  VALUES (
    NEW.id,
    NEW.raw_user_meta_data->>'full_name',
    NEW.raw_user_meta_data->>'phone'
  );

  -- Default role
  INSERT INTO public.user_roles (user_id, role) VALUES (NEW.id, 'user');

  -- Welcome bonus (₹100, already the default profile balance)
  INSERT INTO public.wallet_transactions (user_id, amount, type, description, balance_after)
  VALUES (NEW.id, 100, 'signup_bonus', 'Welcome bonus — 2 free AI reports', 100);

  -- Referral handling
  _ref_code := NULLIF(upper(trim(NEW.raw_user_meta_data->>'referral_code')), '');
  IF _ref_code IS NOT NULL THEN
    SELECT id INTO _referrer_id
    FROM public.profiles
    WHERE upper(referral_code) = _ref_code
      AND id <> NEW.id
    LIMIT 1;

    IF _referrer_id IS NOT NULL THEN
      -- Mark who referred this user
      UPDATE public.profiles SET referred_by = _referrer_id WHERE id = NEW.id;

      -- Credit ₹50 to referrer
      UPDATE public.profiles
      SET wallet_balance = COALESCE(wallet_balance, 0) + 50, updated_at = now()
      WHERE id = _referrer_id
      RETURNING wallet_balance INTO _referrer_new_balance;

      INSERT INTO public.wallet_transactions (user_id, amount, type, description, balance_after)
      VALUES (_referrer_id, 50, 'referral_bonus',
              'Referral bonus — friend joined Stockera',
              _referrer_new_balance);

      -- Credit ₹50 to new user on top of the ₹100 welcome
      UPDATE public.profiles
      SET wallet_balance = COALESCE(wallet_balance, 0) + 50, updated_at = now()
      WHERE id = NEW.id
      RETURNING wallet_balance INTO _referee_new_balance;

      INSERT INTO public.wallet_transactions (user_id, amount, type, description, balance_after)
      VALUES (NEW.id, 50, 'referral_bonus',
              'Referral bonus — joined via friend''s link',
              _referee_new_balance);

      -- Track referral (credited immediately on signup)
      INSERT INTO public.referrals (referrer_id, referred_id, status, payout)
      VALUES (_referrer_id, NEW.id, 'credited', 50);

      -- Notify referrer
      INSERT INTO public.notifications (user_id, title, body, type, link)
      VALUES (_referrer_id,
              '₹50 referral bonus credited',
              'A friend just joined Stockera using your link. ₹50 added to your wallet.',
              'referral',
              '/referral');
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

-- 3) Allow the trigger's INSERT into referrals (currently no INSERT policy).
--    Function is SECURITY DEFINER so it bypasses RLS, but we also add a
--    service_role-only policy for clarity.
DROP POLICY IF EXISTS referrals_service_insert ON public.referrals;
CREATE POLICY referrals_service_insert
  ON public.referrals
  FOR INSERT
  TO service_role
  WITH CHECK (true);
