
-- Phase 2A — Metadata enrichment layer (non-destructive / idempotent)

-- 1) Add nullable columns to public.stock_master if they do not already exist
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'stock_master' AND column_name = 'sector'
  ) THEN
    ALTER TABLE public.stock_master ADD COLUMN sector text;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'stock_master' AND column_name = 'industry'
  ) THEN
    ALTER TABLE public.stock_master ADD COLUMN industry text;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'stock_master' AND column_name = 'market_cap_rs'
  ) THEN
    ALTER TABLE public.stock_master ADD COLUMN market_cap_rs numeric;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'stock_master' AND column_name = 'cap_band'
  ) THEN
    ALTER TABLE public.stock_master ADD COLUMN cap_band text;
  END IF;
END $$;

-- 2) Add CHECK constraint for cap_band idempotently
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE table_schema = 'public'
      AND table_name = 'stock_master'
      AND constraint_name = 'stock_master_cap_band_check'
  ) THEN
    ALTER TABLE public.stock_master
    ADD CONSTRAINT stock_master_cap_band_check
    CHECK (cap_band IS NULL OR cap_band IN ('large', 'mid', 'small', 'micro'));
  END IF;
END $$;

-- 3) Create public.stock_index_membership
CREATE TABLE IF NOT EXISTS public.stock_index_membership (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  symbol text NOT NULL,
  exchange text NOT NULL,
  index_name text NOT NULL,
  as_of_date date NOT NULL,
  source text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 4) Add uniqueness constraint on (symbol, exchange, index_name, as_of_date) idempotently
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes
    WHERE schemaname = 'public'
      AND indexname = 'stock_index_membership_unique'
  ) THEN
    ALTER TABLE public.stock_index_membership
    ADD CONSTRAINT stock_index_membership_unique
    UNIQUE (symbol, exchange, index_name, as_of_date);
  END IF;
END $$;

-- 5) Add useful indexes idempotently
CREATE INDEX IF NOT EXISTS idx_stock_index_membership_index_date
  ON public.stock_index_membership (index_name, as_of_date);

CREATE INDEX IF NOT EXISTS idx_stock_index_membership_symbol_date
  ON public.stock_index_membership (symbol, exchange, as_of_date);

-- 6) Grants for the new table
GRANT SELECT, INSERT, UPDATE, DELETE ON public.stock_index_membership TO authenticated;
GRANT ALL ON public.stock_index_membership TO service_role;

-- 7) Enable RLS
ALTER TABLE public.stock_index_membership ENABLE ROW LEVEL SECURITY;

-- 8) RLS policy: authenticated users can read all rows (public reference data)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename  = 'stock_index_membership'
      AND policyname = 'Authenticated users can read index membership'
  ) THEN
    CREATE POLICY "Authenticated users can read index membership"
      ON public.stock_index_membership
      FOR SELECT
      TO authenticated
      USING (true);
  END IF;
END $$;

-- 9) RLS policy: service_role can do everything
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename  = 'stock_index_membership'
      AND policyname = 'Service role full access on index membership'
  ) THEN
    CREATE POLICY "Service role full access on index membership"
      ON public.stock_index_membership
      FOR ALL
      TO service_role
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;
